#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MangoPlayer.Resource", IsApplication=true)]

namespace MangoPlayer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int LocalWebView = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int menu_OpenInYouTube = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int menu_browseMode = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int menu_browseMode_latest = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int menu_browseMode_topAllTime = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int menu_browseMode_topMonth = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int menu_browseMode_topWeek = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int menu_browseMode_topYear = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int menu_item_share = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int menu_refresh = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int nextButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_to_queue_black = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_autorenew_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_copy_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_cut_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_paste_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_search_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_share_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int BrowseMode = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int BrowseMode_Latest = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int BrowseMode_TopAllTime = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int BrowseMode_TopMonth = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int BrowseMode_TopWeek = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int BrowseMode_TopYear = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int Error_NoVideos = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int MangoPlayer = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int NextButton = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int OpenInYouTubeApp = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int Refresh = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Refreshed = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int Share = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
